version: '3'

services:
  php:
    container_name: php_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    container_name: mysql_container
    build:
      context: .
      dockerfile: Dockerfile_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    

